TAP_DANCE_ENABLE = yes
LTO_ENABLE = yes
SPLIT_KEYBOARD = yes
EXTRAKEY_ENABLE = yes
OLED_DRIVER_ENABLE = no
COMBO_ENABLE = no
MOUSEKEY_ENABLE = yes       # Mouse keys
NKRO_ENABLE = yes           # Enable N-Key Rollover
CAPS_WORD_ENABLE = yes
